# Default values for secoda.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

services:
  api:
    image:
      registry: ""
      name: "on-premise-api"
      pullPolicy: ""
      tag: ""
    command: []
    args: []
    env: []
    ports:
      - containerPort: 5007
    resources:
      requests:
        memory: 4096Mi
        cpu: 1024m
        ephemeral-storage: 64Gi
      limits:
        memory: 8192Mi
        cpu: 2048m
        ephemeral-storage: 64Gi
    livenessProbe:
      tcpSocket:
        port: 5007
    readinessProbe:
      tcpSocket:
        port: 5007
    securityContext: {}

  frontend:
    image:
      registry: ""
      name: "on-premise-frontend"
      pullPolicy: ""
      tag: ""
    args: []
    env: []
    ports:
      - name: https
        containerPort: 443
      - name: http
        containerPort: 80
    resources:
      requests:
        memory: 2048Mi
        cpu: 512m
        ephemeral-storage: 4Gi
    livenessProbe:
      tcpSocket:
        port: 5006
    readinessProbe:
      tcpSocket:
        port: 5006
      initialDelaySeconds: 30
      timeoutSeconds: 5
    securityContext: {}

  redis:
    image:
      registry: "docker.io"
      name: "redis"
      pullPolicy: ""
      tag: "6.2"
    env: []
    ports:
      - containerPort: 6379
    command: ["redis-server"]
    resources:
      requests:
        memory: 1024Mi
        cpu: 256m
        ephemeral-storage: 4Gi
      limits:
        memory: 2048Mi
        cpu: 512m
        ephemeral-storage: 16Gi
    livenessProbe:
      tcpSocket:
        port: 6379
    readinessProbe:
      tcpSocket:
        port: 6379
    securityContext: {}

global:
  image:
    registry: "secoda"
    pullPolicy: Always
    tag: "6"
  env: []
  resources: {}
  securityContext:
    {}
    # allowPrivilegeEscalation: false

persistence:
  enabled: false

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

service:
  type: NodePort

nodeSelector: {}
tolerations: []
affinity: {}
dnsConfig: {}
annotations: {}
